### PR TITLE
New helper function to convert integer baudrate to OS-defined baudrate

### PR DESCRIPTION
**Pull request by dogoepp**
Shall I merge ?

### CODE REVIEW

**Comment by fedeallocati** [comment]
It's good, but I'm not convinced by this part:

```
default:
    os_baudrate = B1000000;
    std::stringstream err_message;
    err_message << "Invalid baudrate: " << os_baudrate << "! Setting to default: 1,000,000 bauds";
    throw Error(err_message.str());
```

When you throw an Exception, you don't get a return value, so it's useless to set os_baudrate, and the message of setting it to default isn't true.

**Comment by dogoepp** [comment]
Right, thanks. I had changed from a ros message and forgot this.

**Comment by fedeallocati** [comment]
Another question. Any reason why setting os_baudrate in the switch, and then returning it, instead of returning it directly in the swicht statement?

**Comment by dogoepp** [comment]
No good reason. I had also though of this option. Do you think it's better ?

**Comment by fedeallocati** [comment]
I just think it's cleaner. Performance-wise, I guess the compiler realises it's the same, doesn't reserve space in the stack for the variable, and instead does return value optimization.

**Comment by dogoepp** [comment]
Anyway it's going to be replaced by v2 very soon.

@jbmouret any remark on this ?

**Comment by costashatz** [comment]
Just merge it.. V2 is almost complete and it doesn't change anything..

**Pull request merged**
