### PR TITLE
add a little precision in ServoLimitError message

### PR DESCRIPTION
**Pull request by elkhadiy**
issue #41

make it more explicit to users that didn't pay attention to the help
that they have to give the angle value in radians

### CODE REVIEW

**Comment by dogoepp** [comment]
Hi @elkhadiy,

Thanks for taking time to look into this relevant issue. Maybe it might be better to switch everything to radians, since it's what is used in the whole API.

**Comment by elkhadiy** [comment]
yeah seems like a good idea, a git grep shows that you guys only seem to use values in deg extracted from the hardware's docs (I'm guessing)

**Comment by dogoepp** [comment]
Thanks a lot for your contribution. It seems all right but I need to test it before it goes into master, since it is used for experiments that can hardly afford a bug.

**Comment by dogoepp** [comment]
I just tested it, all goes well. Do you think that you could rebase your commit on master and fore push the your branch ?

**Pull request merged**
