### PR TITLE
Assertions fix

### PR DESCRIPTION
**Pull request by costashatz**
Replaced assertions with exceptions.

### CODE REVIEW

**Comment by dogoepp** [comment]
Sounds great !

I just have two cents proposals for the error messages in #12. Could you have a look ?

**Comment by costashatz** [comment]
> Sounds great !
> 
> I just have two cents proposals for the error messages in #12. Could you have a look ?

Already did! :smile:

**Comment by dogoepp** [comment]
Thanks :)

**OK for Merger**

**Comment by fedeallocati** [comment]
**Good for me too**

**Pull request merged**
