### PR TITLE
Preliminary version of the Command line Utility

### PR DESCRIPTION
**Pull request by dogoepp**
This version has most of the features we could use on a daily basis.

The missing features are:
- management of speed (target and current)
- elaborate version of the oscillate command (with multiple oscillators)
- instantiation for version 2 of the protocol

I intend to add these features later on.

In the meantime, I would appreciate if you can give me some **feedback** about the utility itself. Is it easy enough to use ? Does it cover your needs ?

Thanks,
Dorian

### CODE REVIEW

**Comment by costashatz** [comment]
> In the meantime, I would appreciate if you can give me some feedback about the utility itself. Is it easy enough to use ? Does it cover your needs ?

I think it has more than what we need... **Good job**

> The missing features are:
> 
> management of speed (target and current)
> instantiation for version 2 of the protocol

We should add this 2, before merging...

**Comment by dogoepp** [comment]
Thanks for the feedback. I agree that speed and version 2 are prerequisite to merging. Will take care of it.

**Comment by dogoepp** [comment]
Since we've been using this version for a long time already and I didn't have time yet to do the version 2 and speed management, I propose that we merge for now.

I'll handle the missing points in a future pull request. OK ?

**Comment by jbmouret** [comment]
Ok

**Comment by costashatz** [comment]
**OK**

**Comment by dogoepp** [comment]
**Merging**

**Pull request merged**
