### PR TITLE
Adding comments to the code

### PR DESCRIPTION
**Pull request by dogoepp**
Ongoing commenting of the code. If you have remarks to make regarding what I wrote, feel free to write them.

### CODE REVIEW

**Comment by dogoepp** [comment]
I'm done for now. This should be harmless. Agreed to merge ?

**Comment by costashatz** [comment]
**Seems good**

**Comment by fedeallocati** [comment]
**Good**. I modified a little StatusPacket and InstructionPacket, to have the Protocol template argument more self explanatory

**Comment by dogoepp** [comment]
Great, thanks! I'm **merging**

**Comment by dogoepp** [comment]
The merge has been done properly on my computer with a rebase. This v2-commented branch is to be deleted (and has some noise).

**Pull request closed without merging**
