### PR TITLE
Utility for Dynamixel Pro actuators

### LINKED ISSUE #20: Make the utility work with Dynamixel Pros
The command line utility provided with this library is written to be compatible with both families of Dynamixel. Yet, it was only compiled for the non-Pro family.

### PR DESCRIPTION
**Pull request by dogoepp**
Fixes #20 (hopefully).

Any other idea than creating one program for each version of the protocol ?

### CODE REVIEW

**Comment by costashatz** [comment]
> Any other idea than creating one program for each version of the protocol ?

If Protocol1 and Protocol2 have the same functionality (i.e. the same commands and only the template changes), then you can use preprocessor directives (#ifdef) to just change the template. You need to modify the wscript to compile 2 targets (with different defines --- it's easy), but the source file will be one.

``` cpp
#ifdef PROTOCOL2
using Protocol = protocols::Protocol2;
#else
using Protocol = protocols::Protocol1;
#endif
typedef Utility<Protocol>::id_t id_t;
....
```

**Comment by jbmouret** [comment]
Yes, we can create 2 binaries from a single file.

## 

Jean-Baptiste Mouret - Inria researcher
www: http://members.loria.fr/JBMouret
ERC ResiBots: http://www.resibots.eu

**Comment by dogoepp** [comment]
Thanks for the advice, done.

**Comment by dogoepp** [comment]
Anything else needing changes ?

**OK to merge** ?

**Comment by costashatz** [comment]
**It's ok for me...**

**Comment by dogoepp** [comment]
OK, will merge, but in another pull request. I messed a bit with the history of this branch.

**Pull request closed without merging**
